### PR TITLE
Added Charger plug models (dae, skp)

### PR DESCRIPTION
**Pull request by BohJieQi**
Charger is the default correct one
ChargerNSF is no safety mark
ChargerFW is the one with the frayed wires

I made a folder in assets containing everything
Sry for inconvenience cause :/

### CODE REVIEW

**Comment by kaine119** [comment]
We don't need the skp files, just upload them on the drive
For the game, just the .dae files will do

**Comment by PohSayKeong** [comment]
In fact you can go ahead and replace the charger file in the models folder directly.
Replace by copy and pasting in file explorer, that should work fine.
Ensure that the file name is the same.
Delete the folder you created before I can merge.

**Comment by kaine119** [comment]
will have to put some colour on the model in Unity as well, i'll try to work on that
you copy the files over first

**Comment by PohSayKeong** [comment]
You should put the color on in SketchUp?
If you are using a material, take not that there is a materials file for you to deposit your materials.
SketchUp saves the material as an image file when you export it, do look out for that.

Side note: it s a charger, what colors do you want to see?

**Pull request closed without merging**
